import type{Cell,Rarity,RunState}from'./model';import{RARITIES}from'./model';import{createRun,transition}from'./run-state';import{purchase,stageReward}from'./economy';import{addUnit,placeOnBoard,sellUnit}from'./roster';import{createBattle,stepBattle,type BattleState}from'./battle';import{ENCOUNTERS}from'./encounters';import{KINDS_BY_RARITY}from'./unit-defs';
type Listener=(s:RunState)=>void;const rank=(r:Rarity)=>RARITIES.indexOf(r);
export class GameController{private state:RunState;private listeners=new Set<Listener>();private active:string[]=[];private battle?:BattleState;private random:number;layout:Rarity[]=['white','blue','purple','orange','red'];
constructor(seed=Date.now(),initial?:RunState){this.state=initial??createRun(seed);this.random=seed>>>0}snapshot(){return this.state}battleSnapshot(){return this.battle}subscribe(fn:Listener){this.listeners.add(fn);fn(this.state);return()=>this.listeners.delete(fn)}private emit(){for(const fn of this.listeners)fn(this.state)}private rand(){this.random=(this.random*1664525+1013904223)>>>0;return this.random/4294967296}
buy(mode:'single'|'five'){const bought=purchase(this.state,mode);this.state=bought.state;this.layout=bought.layout;const start=this.state.ballsFired-bought.count;this.active=Array.from({length:bought.count},(_,i)=>`b${start+i+1}`);this.emit();return{ids:[...this.active],layout:this.layout}}
settleBall(id:string,rarity:Rarity){if(!this.active.includes(id)||this.state.settledBallIds.includes(id))return;const pool=KINDS_BY_RARITY[rarity],kind=pool[Math.floor(this.rand()*pool.length)]!;this.state=addUnit({...this.state,settledBallIds:[...this.state.settledBallIds,id],highestRarity:rank(rarity)>rank(this.state.highestRarity)?rarity:this.state.highestRarity},kind);if(this.active.every(x=>this.state.settledBallIds.includes(x))){this.state={...this.state,phase:'PREP'};this.active=[]}this.emit()}
place(id:string,cell:Cell){this.state=placeOnBoard(this.state,id,cell);this.emit()}sell(id:string){this.state=sellUnit(this.state,id);this.emit()}startBattle(){const board=this.state.units.filter(u=>u.location==='board'&&u.cell);if(!board.length)throw new Error('Deploy a unit');this.state=transition(this.state,'BATTLE');const encounter=ENCOUNTERS[this.state.stage-1]!;const players=board.map(u=>({id:u.id,kind:u.kind,star:u.star,team:'player' as const,row:u.cell!.row,col:u.cell!.col}));const enemies=encounter.enemies.map((u,i)=>({id:`e${this.state.stage}-${i}`,kind:u.kind,star:1 as const,team:'enemy' as const,row:u.row,col:u.col}));this.battle=createBattle(players,enemies,encounter.scale);this.emit()}
tickBattle(ms:number){if(!this.battle||this.state.phase!=='BATTLE')return[];this.battle=stepBattle(this.battle,ms);const events=[...this.battle.events];if(this.battle.winner){if(this.battle.winner==='player'){const gold=this.state.gold+stageReward(this.state.stage);if(this.state.stage===10)this.state={...this.state,gold,phase:'RUN_END',result:'victory'};else this.state={...this.state,gold,stage:this.state.stage+1,phase:'PREP'}}else this.state={...this.state,phase:'RUN_END',result:'defeat'};this.emit()}return events}
restart(seed=Date.now()){this.state=createRun(seed);this.random=seed>>>0;this.active=[];this.battle=undefined;this.emit()}encounter(){return ENCOUNTERS[this.state.stage-1]!}}
