import Phaser from'phaser';import type{GameController}from'../../game/controller';import type{Rarity,RunState,UnitKind}from'../../game/model';import{RARITY_WIDTH}from'../../game/economy';import{isRelaunchReady,PEG_LAYOUT,TRACK}from'../pachinko/geometry';
const RC:Record<Rarity,number>={white:0xe8e8e8,blue:0x48aaff,purple:0xbd61ff,orange:0xffaa42,red:0xff4058};const RN:Record<Rarity,string>={white:'白',blue:'蓝',purple:'紫',orange:'橙',red:'红'};const KN:Record<UnitKind,string>={guard:'盾',swordsman:'剑',axeman:'斧',longbow:'弓',crossbow:'弩',slinger:'投'};
type ActiveBall={img:Phaser.Physics.Matter.Image,lastLaunch:number,nudged:boolean,retryReady:boolean,retryRing?:Phaser.GameObjects.Arc};
export class GameScene extends Phaser.Scene{private c!:GameController;private balls=new Map<string,ActiveBall>();private pocketBodies:any[]=[];private pocketViews:Phaser.GameObjects.GameObject[]=[];private unitViews:Phaser.GameObjects.GameObject[]=[];private selected?:string;private reduced=false;private acc=0;private unsub?:()=>void;
constructor(){super('game')}create():void{this.c=this.registry.get('controller')as GameController;this.input.mouse?.disableContextMenu();this.drawShell();this.buildMachine();this.drawBoard();this.matter.world.on('collisionstart',(e:any)=>this.collide(e));const launch=(e:Event)=>this.launch((e as CustomEvent<'single'|'five'>).detail);window.addEventListener('pk-launch',launch);window.addEventListener('pk-motion',(e:Event)=>this.reduced=(e as CustomEvent<boolean>).detail);this.events.once('shutdown',()=>{window.removeEventListener('pk-launch',launch);this.unsub?.()});this.unsub=this.c.subscribe(s=>this.render(s));document.addEventListener('visibilitychange',()=>{if(document.hidden)this.scene.pause();else if(this.scene.isPaused())this.scene.resume()})}
private drawShell(){this.add.rectangle(332,328,650,640,0x182a36).setStrokeStyle(6,0xd2a456);this.add.rectangle(972,328,610,640,0x183126).setStrokeStyle(6,0xd2a456);this.add.text(332,16,'♛ 王室征兵机',{fontFamily:'monospace',fontSize:'22px',color:'#ffe1a0'}).setOrigin(.5,0);this.add.text(972,16,'⚔ 王国战棋场',{fontFamily:'monospace',fontSize:'22px',color:'#ffe1a0'}).setOrigin(.5,0);this.add.text(332,50,'点击单发 / 五连，弹簧会自动使用当前力度',{fontFamily:'monospace',fontSize:'13px',color:'#9ec7d3'}).setOrigin(.5,0)}
private buildMachine(){const g=TRACK,addWall=(x:number,y:number,w:number,h:number)=>this.matter.add.rectangle(x,y,w,h,{isStatic:true,label:'wall',friction:.02,restitution:.75});addWall(g.leftWallX,330,18,540);addWall(g.outerWallX,330,18,540);const topWidth=g.topBoundaryRight-g.leftWallX;addWall(g.leftWallX+topWidth/2,g.topY,topWidth,16);addWall(g.innerRailX,(g.innerRailTop+g.innerRailBottom)/2,14,g.innerRailBottom-g.innerRailTop);addWall((g.innerRailX+g.outerWallX)/2,g.launchFloorY,g.outerWallX-g.innerRailX,14);this.matter.add.rectangle(g.guide.x,g.guide.y,g.guide.width,g.guide.height,{isStatic:true,label:'guide',angle:g.guide.angle,restitution:.78});for(const row of PEG_LAYOUT)for(const peg of row){this.add.circle(peg.x,peg.y,6,0xdab15f).setStrokeStyle(2,0x71471f);this.matter.add.circle(peg.x,peg.y,6,{isStatic:true,label:'peg',restitution:.88})}this.add.rectangle((g.innerRailX+g.outerWallX)/2,350,g.outerWallX-g.innerRailX-10,430,0xd9b46a,.12).setStrokeStyle(2,0x6f4925);this.add.rectangle(g.innerRailX,(g.innerRailTop+g.innerRailBottom)/2,14,g.innerRailBottom-g.innerRailTop,0x9b6d31).setStrokeStyle(3,0xf2c96f);this.add.rectangle(g.guide.x,g.guide.y,g.guide.width,g.guide.height,0xc99a4c).setRotation(g.guide.angle).setStrokeStyle(3,0xffd77c);this.add.text(620,330,'发\n射\n轨\n道',{fontFamily:'monospace',fontSize:'13px',color:'#e8c87d',align:'center'}).setOrigin(.5);this.rebuildPockets(this.c.layout)}
private rebuildPockets(layout:Rarity[]){for(const b of this.pocketBodies)this.matter.world.remove(b);for(const v of this.pocketViews)v.destroy();this.pocketBodies=[];this.pocketViews=[];let x=35;const total=565;for(const rarity of layout){const w=total*RARITY_WIDTH[rarity]/100,center=x+w/2;const rect=this.add.rectangle(center,596,w-3,70,0x211a20).setStrokeStyle(4,RC[rarity]);const txt=this.add.text(center,587,`${RN[rarity]}\n盲盒`,{align:'center',fontFamily:'monospace',fontSize:w<55?'11px':'15px',color:'#ffffff'}).setOrigin(.5);const body=this.matter.add.rectangle(center,596,w-3,70,{isStatic:true,isSensor:true,label:`pocket:${rarity}`});this.pocketBodies.push(body);this.pocketViews.push(rect,txt);x+=w}}
private launch(mode:'single'|'five'){try{const shot=this.c.buy(mode);this.rebuildPockets(shot.layout);const power=20+Math.sin(this.time.now/520)*2;shot.ids.forEach((id,i)=>this.time.delayedCall(i*200,()=>{const img=this.matter.add.image(TRACK.spawn.x,TRACK.spawn.y,'ball').setCircle(TRACK.spawn.radius).setBounce(.82).setFriction(.001).setFrictionAir(.002).setDepth(5);(img.body as any).label=`ball:${id}`;const ball:ActiveBall={img,lastLaunch:this.time.now,nudged:false,retryReady:false};this.balls.set(id,ball);img.on('pointerdown',()=>this.relaunch(id));this.fire(ball,power*(1+(i-2)*.008))}))}catch(e){this.toast(e instanceof Error?e.message:'无法发射')}}
private fire(ball:ActiveBall,power=20+Math.sin(this.time.now/520)*2){this.clearRetry(ball);ball.img.setAngularVelocity(0);ball.img.setVelocity(Phaser.Math.FloatBetween(-.08,.08),-power);ball.lastLaunch=this.time.now;ball.nudged=false}
private relaunch(id:string){const ball=this.balls.get(id);if(!ball||!ball.retryReady)return;this.fire(ball);this.spark(ball.img.x,ball.img.y);this.toast('再次发射！')}
private showRetry(ball:ActiveBall){ball.retryReady=true;ball.img.setInteractive({useHandCursor:true});const ring=this.add.circle(ball.img.x,ball.img.y,15,0xffd36a,0).setStrokeStyle(2,0xffd36a).setDepth(4);ball.retryRing=ring;this.tweens.add({targets:ring,alpha:{from:.35,to:1},scale:{from:.9,to:1.25},duration:520,yoyo:true,repeat:-1})}
private clearRetry(ball:ActiveBall){ball.retryReady=false;ball.img.disableInteractive();if(ball.retryRing){this.tweens.killTweensOf(ball.retryRing);ball.retryRing.destroy();ball.retryRing=undefined}}
private collide(e:any){for(const p of e.pairs as any[]){const labels=[p.bodyA.label as string,p.bodyB.label as string],ballLabel=labels.find(x=>x.startsWith('ball:')),pocket=labels.find(x=>x.startsWith('pocket:'));if(ballLabel&&pocket){const id=ballLabel.slice(5),rarity=pocket.slice(7)as Rarity;this.settle(id,rarity)}else if(ballLabel&&labels.includes('peg'))this.spark((p.bodyA.position.x+p.bodyB.position.x)/2,(p.bodyA.position.y+p.bodyB.position.y)/2)}}
private spark(x:number,y:number){for(let i=0;i<(this.reduced?2:5);i++){const s=this.add.image(x,y,'spark').setTint(0xffd36a).setScale(.4).setDepth(9);this.tweens.add({targets:s,x:x+Phaser.Math.Between(-16,16),y:y+Phaser.Math.Between(-16,12),alpha:0,duration:220,onComplete:()=>s.destroy()})}}
private settle(id:string,rarity:Rarity){const b=this.balls.get(id);if(!b)return;this.balls.delete(id);this.clearRetry(b);b.img.destroy();this.c.settleBall(id,rarity);const x=330,y=530,t=this.add.text(x,y,`${RN[rarity]}色盲盒！`,{fontFamily:'monospace',fontSize:rarity==='red'?'34px':'24px',fontStyle:'bold',color:`#${RC[rarity].toString(16).padStart(6,'0')}`,stroke:'#160f15',strokeThickness:6}).setOrigin(.5).setDepth(20);if(!this.reduced&&['purple','orange','red'].includes(rarity))this.cameras.main.shake(rarity==='red'?220:120,rarity==='red'?.012:.006);this.tweens.add({targets:t,y:y-95,scale:rarity==='red'?1.35:1,alpha:0,duration:rarity==='red'?1200:650,onComplete:()=>t.destroy()})}
private drawBoard(){for(let row=0;row<4;row++)for(let col=0;col<6;col++){const x=708+col*90,y=88+row*88,r=this.add.rectangle(x+43,y+41,84,82,(row+col)%2?0x625b43:0x817653).setStrokeStyle(2,col<3?0x6fa3b0:0xad6a6a).setInteractive({useHandCursor:true});r.on('pointerdown',()=>{if(this.selected)try{this.c.place(this.selected,{row:row as 0|1|2|3,col:col as 0|1|2|3|4|5});this.selected=undefined}catch(e){this.toast(e instanceof Error?e.message:'不能放这里')}})}this.add.text(974,452,'备战席 · 点击单位后再点击左半区格子布阵',{fontFamily:'monospace',fontSize:'14px',color:'#d9c58e'}).setOrigin(.5)}
private clearUnits(){for(const v of this.unitViews)v.destroy();this.unitViews=[]}
private unit(x:number,y:number,label:string,color:number,enemy=false,stars=1,hp=1){const ring=this.add.circle(x,y,27,color,.25).setStrokeStyle(3,color).setDepth(5),body=this.add.rectangle(x,y,34,42,enemy?0xb64b52:0x4781bd).setStrokeStyle(3,enemy?0x64222b:0x173e6a).setDepth(6),text=this.add.text(x,y-2,label,{fontFamily:'monospace',fontSize:'17px',fontStyle:'bold',color:'#fff'}).setOrigin(.5).setDepth(7),star=this.add.text(x,y+27,'★'.repeat(stars),{fontFamily:'monospace',fontSize:'10px',color:'#ffd66b'}).setOrigin(.5).setDepth(7),bar=this.add.rectangle(x,y-31,50,5,0x1c1517).setDepth(7),fill=this.add.rectangle(x-25+25*hp,y-31,50*hp,5,0x67d46f).setDepth(8);this.unitViews.push(ring,body,text,star,bar,fill);return body}
private render(s:RunState){if(s.phase==='BATTLE'){this.renderBattle();return}this.clearUnits();const enc=this.c.encounter();for(const e of enc.enemies)this.unit(751+e.col*90,129+e.row*88,KN[e.kind],0xd84b58,true);for(const u of s.units){const color=RC[u.rarity];if(u.location==='board'&&u.cell){const body=this.unit(751+u.cell.col*90,129+u.cell.row*88,KN[u.kind],color,false,u.star);body.setInteractive({useHandCursor:true}).on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.rightButtonDown())this.c.sell(u.id);else{this.selected=u.id;this.render(this.c.snapshot())}});if(this.selected===u.id)body.setStrokeStyle(6,0xffffff)}else if(u.location==='bench'||u.location==='recruit'){const i=u.location==='bench'?u.benchIndex??0:11,x=723+(i%6)*91,y=500+Math.floor(i/6)*66;const body=this.unit(x,y,KN[u.kind],color,false,u.star);body.setScale(.82).setInteractive({useHandCursor:true}).on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.rightButtonDown())this.c.sell(u.id);else{this.selected=u.id;this.render(this.c.snapshot())}});if(this.selected===u.id)body.setStrokeStyle(6,0xffffff)}}}
private renderBattle(){const b=this.c.battleSnapshot();if(!b)return;this.clearUnits();for(const f of b.fighters.filter(x=>x.hp>0))this.unit(751+f.col*90,129+f.row*88,KN[f.kind],f.team==='enemy'?0xd84b58:RC[f.rarity],f.team==='enemy',f.star,Math.max(0,f.hp/f.maxHp))}
update(_:number,delta:number){for(const[id,b]of this.balls){const body=b.img.body as any,speed=body&&'speed'in body?body.speed:999,elapsed=this.time.now-b.lastLaunch,ready=isRelaunchReady(b.img.x,b.img.y,body?.velocity?.y??-999,elapsed);if(ready&&!b.retryReady)this.showRetry(b);else if(!ready&&b.retryReady)this.clearRetry(b);if(b.retryRing)b.retryRing.setPosition(b.img.x,b.img.y);if(elapsed>2000&&!b.nudged&&speed<.25&&!b.retryReady){b.img.applyForce(new Phaser.Math.Vector2(Phaser.Math.FloatBetween(-.004,.004),-.004));b.nudged=true}if(elapsed>10000)this.settle(id,this.c.layout[2]??'white')}if(this.c.snapshot().phase==='BATTLE'){this.acc+=Math.min(delta,100);while(this.acc>=50){this.c.tickBattle(50);this.acc-=50}if(this.c.snapshot().phase==='BATTLE')this.renderBattle()}}
private toast(text:string){const t=this.add.text(640,620,text,{fontFamily:'monospace',fontSize:'17px',backgroundColor:'#211318',padding:{x:12,y:7},color:'#ffd68a'}).setOrigin(.5).setDepth(30);this.tweens.add({targets:t,alpha:0,y:590,duration:1400,onComplete:()=>t.destroy()})}}
